name: TEST-912

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'  # or 'temurin' depending on your preference

    - name: Set up ChromeDriver
      run: |
        wget -N https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium test
      run: |
        javac -cp ".:libs/*" automationtest/Selenium.java
        java -cp ".:libs/*" automationtest.Selenium
